## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [8]:
import traceback

def computeDevision():
        try:
            val = 5/0
        except:
            print("Caught an exception")  
            traceback.print_exc()
        
computeDevision()        

Caught an exception


Traceback (most recent call last):
  File "<ipython-input-8-7215527ef6ce>", line 5, in computeDevision
    val = 5/0
ZeroDivisionError: division by zero


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [69]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i,j,k)


Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [67]:
import numpy as np

def vectorProgression(array, n, order):
    tempArr = np.ones((len(array),n),np.int)
#     print(tempArr)
#     print(tempArr*np.vstack(array))
    tempArr = tempArr*np.vstack(array)
#     print(tempArr.shape)
    if(order):
        for i in range(len(array)):
#             print(tempArr[i], len(tempArr[i]))
            for j in range(len(tempArr[i])):
                tempArr[i][j] = tempArr[i][j] ** j
    else :
        for i in range(len(array)):
#             print(tempArr[i], len(tempArr[i]))
            for j in range(len(tempArr[i])):
                tempArr[i][j] = tempArr[i][j] ** (N - j - 1)
    
    
    
    return tempArr

x = np.array([1, 2, 3, 6])
N = 5
print(vectorProgression(x,N,False))
# np.vander(x, N, increasing=False)

[[   1    1    1    1    1]
 [  16    8    4    2    1]
 [  81   27    9    3    1]
 [1296  216   36    6    1]]


array([[   1,    1,    1,    1,    1],
       [  16,    8,    4,    2,    1],
       [  81,   27,    9,    3,    1],
       [1296,  216,   36,    6,    1]])